name: terraform plan and apply

on:
  push:
    paths: 
      - 'Terraform_workflow/env/**'
  

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  checkov:
    name: Checkov Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Checkov scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: Terraform_workflow/env
          output_format: cli  
  plan:
    needs: checkov
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, test]   
    env:
      TF_WORKING_DIR: Terraform_workflow/env/${{ matrix.env }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.7'

      - name: Terraform Init
        run: |
          cd $TF_WORKING_DIR
          terraform init -input=false \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=envs/${{ matrix.env }}/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Terraform Format & Validate
        run: |
          cd $TF_WORKING_DIR
          terraform fmt -check || true
          terraform validate

      - name: Terraform Plan
        run: |
          cd $TF_WORKING_DIR
          terraform plan -input=false -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Upload plan.txt
        uses: actions/upload-artifact@v4
        with:
           name: plan-text-${{ matrix.env }}
           path: ${{ env.TF_WORKING_DIR }}/plan.txt
  
  terraform_apply:
    needs: plan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, test]   
    env:
      TF_WORKING_DIR: Terraform_workflow/env/${{ matrix.env }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.5.7'

      - name: Terraform Init
        run: |
          cd $TF_WORKING_DIR
          terraform init -input=false \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="key=envs/${{ matrix.env }}/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Terraform Plan & Apply
        run: |
          cd $TF_WORKING_DIR
          terraform plan -input=false -out=tfplan
          terraform apply -auto-approve tfplan
